# -*- coding: utf-8 -*-
"""Type 2 Diabetes_Gene_Expression_Project_AM

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G5tKKF52bcEl08AKa81oMmB5s6q1Eozu
"""

from google.colab import files

uploaded = files.upload()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier

from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

import os

os.listdir()

df= pd.read_csv("GSE20966_series_matrix.txt", sep="\t", comment="!")
df.head()

df.shape

df.columns

gene_names = df["ID_REF"]
gene_names.head()

expression = df.drop("ID_REF", axis=1)
expression.head()

X = expression.T
X.columns = gene_names
X.head()

X.shape

X.isnull().sum().sum()

labels = [
0,0,0,0,0,
0,0,0,0,0,

1,1,1,1,1,
1,1,1,1,1
]

len(labels), X.shape[0]

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

X_scaled_df = pd.DataFrame(X_scaled, columns=X.columns)

X_scaled_df.head()

pca = PCA(n_components=2)

pca_result = pca.fit_transform(X_scaled)

pca_df = pd.DataFrame(pca_result, columns=["PC1", "PC2"])

pca_df["Class"] = labels

#PCA graph

plt.figure(figsize=(8,6))

sns.scatterplot(data=pca_df,  x="PC1",y="PC2", hue="Class", s=100)

plt.title("PCA Analysis of GSE20966 Gene Expression")

plt.show()

variance = X_scaled_df.var()

top_genes = variance.sort_values(ascending=False).head(50).index

#Heatmap

plt.figure(figsize=(12,8))


sns.heatmap(X_scaled_df[top_genes].T, cmap="coolwarm", cbar=False)

plt.xlabel("Samples")

plt.ylabel("Genes"

plt.title("Top 50 Variable Genes")

plt.show()

X_original = pd.DataFrame(X, columns=X.columns)

diabetes_samples = X_original.iloc[10:]

control_samples = X_original.iloc[:10]

diabetes_mean = diabetes_samples.mean()

control_mean = control_samples.mean()

fold_change = diabetes_mean - control_mean

top_changed_genes = fold_change.sort_values(ascending=False).head(20)

top_changed_genes

X_train, X_test, y_train, y_test = train_test_split(X_scaled, labels, test_size=0.2, random_state=42)

rf = RandomForestClassifier(n_estimators=100,random_state=42)


rf.fit(X_train,y_train)


rf_prediction = rf.predict(X_test)

rf_accuracy = accuracy_score(y_test,rf_prediction)


rf_accuracy

svm = SVC()

svm.fit(X_train, y_train)


svm_prediction = svm.predict(X_test)

svm_accuracy = accuracy_score( y_test, svm_prediction)

svm_accuracy

dt = DecisionTreeClassifier(random_state=42)

dt.fit(X_train, y_train)


dt_prediction = dt.predict(X_test)

dt_accuracy = accuracy_score(y_test, dt_prediction)

dt_accuracy

results = pd.DataFrame({"Model":["Random Forest","SVM","Decision Tree"],"Accuracy":[rf_accuracy,svm_accuracy,dt_accuracy]})

results